services:
  - type: web
    name: alberto-portfolio
    env: node
    buildCommand: DEPLOY_TARGET=node npm run build
    startCommand: node ./dist/server/entry.mjs
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: TURNSTILE_SECRET_KEY
        sync: false
