services:
  - type: web
    name: alberto-portfolio
    env: node
    buildCommand: make build
    startCommand: make start
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: TURNSTILE_SECRET_KEY
        sync: false
